### ISSUE TITLE
Do you have further plans to develop this extension?

### ISSUE THREAD

**Issue by THUzxj** [RabbitWhite1/p4-lang-vscode#1]
Hi,
       I am a starter in P4 language and I am looking for a language highlighting tool in vscode for P4-16. I have done something in developing a new extension which is [p4-16-vscode](https://github.com/THUzxj/P4-16-vscode) and then I find your repo.😂
       Do you have some plans to develop recently? If you have, could I take part in your project? If not, I'll continue to develop in my repository. I think we can also communicate some experience in P4 study~
       Thank you very much!

**Comment by RabbitWhite1** [comment]
Actually I don't have a concrete plan for now. But I do really want to develop a new extension for p4 lang. I've send my qq number to your email, so that we can have a further chatting.
And there is another [repository](https://github.com/fattaholmanan/p4-vscode-extension) that has a nearly complete ANTLR codes that might help us.
